---
title: "Dropdown Test"
author: "Nosa Lawani"
date: "6/22/2021"
---

```{r code for plots}
website <- read_html("https://www.iihs.org/topics/fatality-statistics/detail/teenagers#alcohol-involvement")
alldata <- website %>% 
  minimal_html() %>% 
  html_elements("#alcohol-involvement .is-fullwidth:nth-child(4) th , #alcohol-involvement .is-fullwidth:nth-child(4) td") %>% 
  html_text2() 

  year <- alldata[seq(27, 520, 13)]
  drivers_killed_16_17 <- alldata[seq(28, 520, 13)]
  bac_16_17 <- alldata[seq(29, 520, 13)]
  bac_perc_16_17 <- alldata[seq(30, 520, 13)]
  drivers_killed_18_20 <- alldata[seq(31, 520, 13)]
  bac_18_20 <- alldata[seq(32, 520, 13)]
  bac_perc_18_20 <- alldata[seq(33, 520, 13)]
  drivers_killed_21_30 <- alldata[seq(34, 520, 13)]
  bac_21_30 <- alldata[seq(35, 520, 13)]
  bac_perc_21_30 <- alldata[seq(36, 520, 13)]
  drivers_killed_30 <- alldata[seq(37, 520, 13)]
  bac_30 <- alldata[seq(38, 520, 13)]
  bac_perc_30 <- alldata[seq(39, 520, 13)]
  
  tibble(year, drivers_killed_16_17, bac_16_17, bac_perc_16_17, 
         drivers_killed_18_20, bac_18_20, bac_perc_18_20, 
         drivers_killed_21_30, bac_21_30, bac_perc_21_30,
         drivers_killed_30, bac_30, bac_perc_30) %>% 
    mutate(across(everything(), ~ str_replace_all(., ",", "")))
```

```{r save images, include=FALSE}
# Save images to computer 

ggsave("images/plot1.png", plot1)
ggsave("images/plot2.png", plot2)


# Make vector of files for menu. Name vector items the label you desire for the 
# option in the menu. 

plots <- c(`Plot 1` = "images/plot1.png",
  `Plot 2` = "images/plot2.png")
```

```{r use bsselect}
bsselect(plots, type = "img", selected = "Plot 1",
         show_tick = TRUE)
```



